### ISSUE TITLE
Create a plugin for expression engine in php7 that worked in php5

### ISSUE THREAD

**Issue by orso081980** [EasyPost/easypost-php#59] opened 2018-04-16 19:58 UTC
I built a nice plugin for ExpressionEngine, which works on PHP 5 but is not working on PHP 7. The problem is that I'm receiving this error:

Fatal error: Uncaught EasyPost\Error: Could not determine which URL to request: EasyPost\Shipment instance has an invalid ID

Essentially, for some reason, I'm not able to get any response from the API because my shipment_id is not returned so my $shipment doesn't receive a shipment_id for some reason, things that didn't happen in php5.

Here's my code:

```
public function store_checkout_form_validation($str, $obj)
    {

        if (ee()->extensions->last_call !== false) {
            $obj = ee()->extensions->last_call;
        }

        if (isset($_POST['easyflag']) == 1) {

            if ($obj->billing_country == '' || $obj->billing_address1 == '' || $obj->billing_city == '' || $obj->billing_state == '' || $obj->billing_postcode == '' || $obj->billing_phone == '') {
                $message['error'] = "All Fields are required";
                echo json_encode($message);
                exit();

            }

            if ($obj->shipping_same_as_billing == '0' && ($obj->shipping_country == '' || $obj->shipping_address1 == '' || $obj->shipping_city == '' || $obj->shipping_state == '' || $obj->shipping_postcode == '' || $obj->shipping_phone == '')) {
                $message['error'] = "All Fields are required";
                echo json_encode($message);
                exit();

            }

            try
            {

                $response = $this->shipment_test($obj);

                if ($response['error']) {

                    $error['error'] = $response['error'];
                    echo json_encode($error);
                    exit();
                    $this->ee->output->show_user_error(false, array($response['error']));

                }

                if ($response['rates']) {

                    foreach ($response['rates'] as $key => $value) {
                        $option         = new OrderShippingMethod;
                        $option->id     = $key;
                        $option->class  = $value->carrier . ':' . $value->id . ':' . $value->shipment_id;
                        $option->name   = $value->service;
                        $option->days   = $value->delivery_days;
                        $option->amount = $value->rate;
                        $obj[$key] = $option;

                    }

                }

                if ($response['rates']) {
                    foreach ($response['rates'] as $key => $value) {
                        $rates[] = array(
                            'shipment_id' => $response['shipment_id'],
                            'rate_id'     => $value->id,
                            'service'     => $value->service,
                            'days'        => $value->delivery_days,
                            'rate'        => $value->rate,
                            'currency'    => $value->currency,
                            'carrier'     => $value->carrier,
                        );

                    }
                    $obj['rates'] = $rates;
                }

            } catch (Exception $e) {
                $messages['error'] = $e->getMessage();
                echo json_encode($messages);
                exit();
                $this->ee->output->show_user_error(false, array($messages));
            }

        }

        return $obj;
    }
```

Where my shipment_test is this function:

```
public function shipment_test($param)
    {

        if ($param['shipping_same_as_billing'] == 1) {

            $data['to_address'] = array(
                "verify"  => array("delivery"),
                "street1" => $param['billing_address1'],
                "street2" => isset($param['billing_address2']) ? $param['billing_address2'] : $param['billing_address1'],
                "city"    => $param['billing_city'],
                "state"   => $param['billing_state'],
                "zip"     => $param['billing_postcode'],
                "country" => $param['billing_country'],
                "company" => $param['billing_name'],
                "phone"   => $param['billing_phone'],
            );

        } else {

            $data['to_address'] = array(
                "verify"  => array("delivery"),
                "street1" => $param['shipping_address1'],
                "street2" => isset($param['shipping_address2']) ? $param['shipping_address2'] : $param['shipping_address1'],
                "city"    => $param['shipping_city'],
                "state"   => $param['shipping_state'],
                "zip"     => $param['shipping_postcode'],
                "country" => $param['shipping_country'],
                "company" => $param['shipping_name'],
                "phone"   => $param['shipping_phone'],
            );

        }

        try
        
        {

            $to_address = \EasyPost\Address::create_and_verify($data['to_address'], $this->apikey);

        } catch (Exception $e) {

            if (!empty($e->errors)) {

                foreach ($e->errors as $error) {
                    $message['error'] .= $error['message'] . '.. ';
                }

            }

            return $message;

        }

        $data['from_address'] = array(
            "verify_strict" => array("delivery"),
            "company"       => "Olivers Learning",
            "street1"       => "151 Bloor Street West, Suite 800",
            "city"          => "Toronto",
            "state"         => "Ontario",
            "zip"           => "M5S1S4",
            "country"       => "CA",
            "phone"         => "4169229604",
        );

        $from_address = \EasyPost\Address::create_and_verify($data['from_address'], $this->apikey);

        $parcel = \EasyPost\Parcel::create(
            array(
                "height" => 12,
                "length" => 10,
                "width"  => 6,
                "weight" => 105.822,
            )
        );

        $custominfo = $this->custom_info($param);

        try
        {
            if ($param['shipping_country'] == 'CA') {
                $shipment = \EasyPost\Shipment::create(array(
                    "to_address"   => $to_address,
                    "from_address" => $from_address,
                    "parcel"       => $parcel,
                    "reference"    => $param->id,

                ));

            } else {
                $shipment = \EasyPost\Shipment::create(array(
                    "to_address"   => $to_address,
                    "from_address" => $from_address,
                    "customs_info" => $custominfo,
                    "parcel"       => $parcel,
                    "reference"    => $param->id,

                ));
            }

            if (!empty($shipment->messages) && empty($shipment->rates)) {

                foreach ($shipment->messages as $rate) {

                    $message['error'][] = $rate->carrier . ":" . $rate->message . "<br/>";

                }

            } else {

                $message['rates']       = $shipment->rates;
                $message['shipment_id'] = $shipment->id;
                $_SESSION['rates']      = $shipment;

            }

        } catch (Exception $e) {

            if (!empty($e->errors)) {
                foreach ($e->errors as $error) {
                    $message['error'] .= $error['message'] . '. ';
                }
            }

        }

        return $message;

    }
```
Right after I return $message, which looks like the shipment object, I call another function in order to retrieve my shipment object like that:

```
public function shipment_buy($shipping_id, $shipping_rate)
    {
        
        $shipments = \EasyPost\Shipment::retrieve(array('id' => $shipping_id), $this->apikey);
        
        try
        {
            $responses                 = $shipments->buy(array('rate' => array('id' => $shipping_rate)));
            $response['tracking_code'] = $responses->tracking_code;
            $response['shipping_id']   = $responses->id;

        } catch (Exception $e) {

            $responses['error'] = $e->getMessage();
        }

        return $responses;

    }

    public function get_shipment($shipping_id)
    {
        $shipments = \EasyPost\Shipment::retrieve($shipping_id);
        return $shipments;
    }
```

As I declared from the very beggining everything works fine in php 5, is there a way to spot my mistake?

**Comment by Justintime50** [comment] 2020-03-09 16:53
Hey @orso081980 is this still an issue for you? Could your provide your entire script if so as testing with pieces is difficult. It appears this is a duplicate of #58, could you close one of them?

**Comment by Justintime50** [comment] 2020-07-24 05:18
Closing as this is a duplicate.

**Closed by Justintime50** 2020-07-24 05:18 UTC
